### ISSUE TITLE
EF tests tracking issue

### ISSUE THREAD

**Issue by lazcanoluca** [lambdaclass/evm_mlir#414]
📂  **General State Tests**
- [ ] Cancun/stEIP1153-transientStorage
- [ ] Cancun/stEIP4844-blobtransactions
- [ ] Cancun/stEIP5656-MCOPY
- [ ] Pyspecs/berlin/eip2930_access_list
- [ ] Pyspecs/byzantium/eip198_modexp_precompile
- [ ] Pyspecs/cancun/eip1153_tstore
- [ ] Pyspecs/cancun/eip4844_blobs
- [ ] Pyspecs/cancun/eip5656_mcopy
- [ ] Pyspecs/cancun/eip6780_selfdestruct
- [ ] Pyspecs/cancun/eip7516_blobgasfee
- [ ] Pyspecs/frontier/opcodes
- [ ] Pyspecs/homestead/yul
- [ ] Pyspecs/istanbul/eip1344_chainid
- [ ] Pyspecs/shangai/eip3651_warm_coinbase
- [ ] Pyspecs/shangai/eip3855_push0
- [ ] Pyspecs/shangai/eip3860_initcode
- [ ] VMTests/vmArithmeticTest
- [ ] VMTests/vmBitwiseLogicOperation
- [ ] VMTests/vmIOandFlowOperations
- [ ] VMTests/vmLogTest
- [ ] VMTests/vmPerformance
- [ ] VMTests/vmTests
- [ ] stArgsZeroOneBalance
- [ ] stAttackTest
- [ ] stBadOpcode
- [ ] stBugs
- [ ] stCallCodes
- [ ] stCallCreateCallCodeTest
- [ ] stCallDelegateCodesCallCodeHomestead
- [ ] stChainId
- [ ] stCodeCopyTest
- [ ] stCodeSizeLimit
- [ ] stCreate2
- [ ] stCreateTest
- [ ] stDelegatecallTestHomestead
- [ ] stEIP150Specific
- [ ] stEIP150singleCodeGasPrices
- [ ] stEIP1559
- [ ] stEIP158Specific
- [ ] stEIP2930
- [ ] stEIP2930
- [ ] stEIP3607
- [ ] stExample
- [ ] stExtCodeHash
- [ ] stHomesteadSpecific
- [ ] stInitCodeTest
- [ ] stLogTests
- [ ] stMemExpandingEIP150Calls
- [ ] stMemoryStressTest
- [ ] stMemoryTest
- [ ] stNonZeroCallsTest
- [ ] stPreCompiledContracts
- [ ] stPreCompiledContracts2
- [ ] stQuadraticComplexityTest
- [ ] stRandom
- [ ] stRandom2
- [ ] stRecursiveCreate
- [ ] stRefundTest
- [ ] stReturnDataTest
- [ ] stRevertTest
- [ ] stSLoadTest
- [ ] stSStoreTest
- [ ] stSelfBalance
- [ ] stShift
- [ ] stSolidityTest
- [ ] stSpecialTest
- [ ] stStackTests
- [ ] stStaticCall
- [ ] stStaticFlagEnabled
- [ ] stSystemOperationsTest
- [ ] stTimeConsuming
- [ ] stTransactionTest
- [ ] stTransitionTest
- [ ] stWalletTest
- [ ] stZeroCallsRevert
- [ ] stZeroCallsTest
- [ ] stZeroKnowledge
- [ ] stZeroKnowledge2
